{% set name = "xerces-c28" %}
{% set version = "2.8.0" %}
{% set sha256 = "416eaf74bbe6ff3b3c64a282e886810cad6cbb48478d3c83344661504c09c8d6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://archive.apache.org/dist/xerces/c/2/sources/xerces-c-src_2_8_0.tar.gz
  sha256: {{ sha256 }}
  # OS X patch from: https://issues.apache.org/jira/secure/attachment/12372362/macsvn.diff
  patches:
    - macsvn.diff  # [osx]

build:
  number: 1002
  skip: true  # [win]
  ignore_run_exports:
    # See below.
    - xerces-c
  run_exports:
    - {{ pin_subpackage('xerces-c28', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    # We include xerces-c as a build-time dep to make sure that we don't overwrite
    # any of its files.
    - xerces-c

test:
  commands:
    - test -f ${PREFIX}/lib/libxerces-c.so.28  # [linux]
    - test -f ${PREFIX}/lib/libxerces-c.28.dylib  # [osx]

about:
  home: http://xerces.apache.org/xerces-c/
  license: Apache 2.0
  license_file: LICENSE.txt
  summary: 'An outdated version of the Xerces XML parsing framework'

extra:
  recipe-maintainers:
    - pkgw
