appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: FS6KRdioG+qM482FJ8G+hC0T4OHWuEmEGuIF5iPX2kx1cBdsTyCVLGsJh7kwJbSNaLLimQb4+xp1uPRwQJm3+11tkEblnXMZ1VmTlJTDdNAKSDIa5oUN1AX+Ts5gN0KYkRBD4wHTHkSqPlNjVISNW8bHQwgBmp03qjIM000QFWwG/FsXKA91kXpLcDzesCdxlNfPMuBfxkDRrMNXyF95nJgeelU3hw5s9UbjJ4nE8WAVCB4DAERIEe8o0/pGmCKEUR6x2kXiK08U5PRE0nbFEyk7khG6TtvmqZ0cFYQZqZyHEClCeiDJVJJTB5ZXr5v3XU31QeitDotqPFFrUYha7Z5U/PZhY77X7DLi8xc7wwCA4hbBs8Tb9ZLbRjm+aFbSMWN9kcmIcIywiXb5N9c/zXdRZwlatXrmHZ+FAzo3JayPnrM0nT4YpXzfovW6spEo5z1ZA0xpoA8Ixm5VF6e8G78mAdzhx061lZlPIm46PwcoeslP2sHZF7GEG0UGIZTOk1jmk1KAhGz/sAlG/UW6SFDb/pazHMIC6zJk47roekb+qGXmE46tZIcQypnaj7BTRDSEoONkUDx+TECCYqXaF8LGiMkUotCTgcpQs+4dQVln32thHbQrEo0NLa+P+2Em27om0gXREzLCazbQJLoXL7Q8dq+FJS4M4hXBSApI4Eo=}
