travis:
  secure:
    BINSTAR_TOKEN: Gvdk6zyH29Mkx7E3zZmVei59XEwhzJ2anFo+eunPCQe+XNhFOA1UA4o1imBoZm0TMEuhoEGXjusMc2T6dpKuuNTpiCz2I/aGbQZVfo+ZghF2vYffxRnjhJxhz+efjS6y54VL9Udnyh/AJBKwGduJkUk6ZgGFQlq3mPH20pLC47zNZaUvWByYkpTB1lfKOGdkAI5cwo6+BWAZQsbkH677ELGfSX1XmDvo6VuXbEEHLAe0GCIhwT+AQKoLv6CpC/7dZ/2oWPIZOL5CuQnyfFsXv42PxCArxeNRyxPFIMOTfoh75P6DstAqqcw419AgsR1rRQQLs/+eMsR0k8p87L5KtNG1lxsDD84O41563MqP1goSqg7Q00UklUeagHOVhfqSmkDDdCtBOH302R2PxSHRK20GJTkCOJazg06J9QM0Cycvzjg6iXR6LLB3LjB0kyfvLc/tGC1vaW9W1dRcL8LyoXNuiUhi9u0kgQALqlC29Z0oXTS1EezSooQdymX8J92feC44zzeGEgt9zbNpNWaJkQjUwMOP1SgzO/cZ7Q8VZPQ32hM2wWM2IFJrgsVlVKi5ADXONyFoOS+bKfr6BeBjvyoK4LyPSSvqAsQG0cqM05ehRvJknLmeTL56Ki6SrM4dn93QFgPhi3WKQ+ZGEm2O+U0c7pexGZIaMGuMe1OQB0c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
